version: '3.1'
services:

# Postgres Database
  postgres-server:
    image: postgres:latest
    restart: always
    ports:
        - 5432:5432
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbixDB
      PG_DATA: /var/lib/postgresql/data/pgdata

# main Zabbix Server
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:ubuntu-latest
    restart: always
    environment:   # The Postgres database value variable
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbixDB
      ZBX_HISTORYSTORAGETYPES: log,text #Zabbix configuration variables
      ZBX_DEBUGLEVEL: 1
      ZBX_HOUSEKEEPINGFREQUENCY: 1
      ZBX_MAXHOUSEKEEPERDELETE: 5000
    depends_on:
      - postgres-server
    volumes:  # Volumes for scripts and related files you can add
      - /usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts

# main Zabbix web interface http://0.0.0.0:8090/
  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-latest
    restart: always
    environment:  # Postgre database variables
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbixDB
      ZBX_SERVER_HOST: zabbix-server
      ZBX_POSTMAXSIZE: 64M
      PHP_TZ: "Europe/Moscow"
      ZBX_MAXEXECUTIONTIME: 500
    depends_on:
      - postgres-server
      - zabbix-server
    ports:
      - 8090:80

# Zabbix agent service usage to zabbix server
  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    privileged: true
    network_mode: "host"
    restart: unless-stopped
    environment:
      - ZBX_SERVER_HOST=127.0.0.1

#Adminer http://0.0.0.0:8090/
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres-server

#Grafana XXL http://0.0.0.0:3000/ по умолчанию - admin / admin
  grafana-xxl:
    image: monitoringartist/grafana-xxl:latest
    ports:
      - 3000:3000
