version: '3.1'
services:

# Postgres Database
  postgres-server:
    image: postgres:latest
    container_name: postgres-server
    restart: always
    ports:
        - 5432:5432
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbixdb
#      PG_DATA: /var/lib/postgresql/data/pgdata
#      volumes:
#        - ./src/postgresql:/var/lib/postgresql/data/pgdata

# Zabbix Server
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:ubuntu-latest
    container_name: zabbix-server
    restart: always
    ports:
      - 10051:10051
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbixdb
      DB_SERVER_HOST: postgres-server
      ZBX_HISTORYSTORAGETYPES: log,text
      ZBX_DEBUGLEVEL: 1
      ZBX_HOUSEKEEPINGFREQUENCY: 1
      ZBX_MAXHOUSEKEEPERDELETE: 5000
    links:
      - postgres-server
    depends_on:
      - postgres-server

# Zabbix web interface http://0.0.0.0:8090/ Login/Password: Admin/zabbix
  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-latest
    container_name: zabbix-web
    restart: always
    ports:
        - 8090:80
        - 443:443
    environment:  # Postgres database variables
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbixdb
      DB_SERVER_HOST: postgres-server
      ZBX_SERVER_HOST: zabbix-server
      ZBX_POSTMAXSIZE: 64M
      PHP_TZ: "Europe/Moscow"
      ZBX_MAXEXECUTIONTIME: 500
    links:
      - zabbix-server
    depends_on:
      - postgres-server
      - zabbix-server

#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:8090/" ]
#      interval: 10s
#      timeout: 5s
#      retries: 3
#      start_period: 30s


## Zabbix agent service
#  zabbix-agent:
#    image: zabbix/zabbix-agent:latest
#    container_name: Zabbix agent
#    privileged: true
#    network_mode: "host"
#    restart: unless-stopped
#    environment:
#      - ZBX_SERVER_HOST=127.0.0.1

#Adminer http://0.0.0.0:8090/
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
        - 8080:8080
    depends_on:
      - postgres-server

##Grafana XXL http://0.0.0.0:3000/ по умолчанию - admin / admin
#  grafana-xxl:
#    image: monitoringartist/grafana-xxl:latest
#    container_name: Grafana
#    ports:
#        - 3000:3000
